### ISSUE TITLE
Make it work with ASAR

### ISSUE THREAD

**Issue by sindresorhus** [karaggeorge/hide-desktop-icons#4]
Since you're using `execa`, which uses `spawn` underneath, you need an extra step to make it work with ASAR. Kap is currently broken when built because of this.

See: https://github.com/sindresorhus/do-not-disturb/commit/12f2aa9ed40f47b8a89e5bf440f11de5891fff1a

**Comment by karaggeorge** [comment]
Fixed in: https://github.com/karaggeorge/hide-desktop-icons/commit/71c477e855406dc5310d1f18305054bb35b503c3
